[package]
name = "rust_brainf7ck_interpreter"
version = "0.1.0"
authors = ["Petar Popov <p.dim.popov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
